apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      software: light-reverse-proxy

  replicas: 2
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        software: light-reverse-proxy
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

