apiVersion: v1
kind: Pod

metadata:
  name: nginx
  labels: 
    software: reverse-proxy

spec:
  containers:
  - name: nginx1
    image: nginx
    ports:
      - containerPort: 80

  - name: tomcat
    image: tomcat:8

    ports:
      - containerPort: 8080

